name: Symfony 6.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/test
      with:
        symfony_version: '6.0'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
